# Generated by Django 5.1.5 on 2025-07-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosource',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videosource',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='yolo_model_path',
            field=models.CharField(default='my_model (2).pt', max_length=500),
        ),
    ]
