# Generated by Django 5.1.5 on 2025-07-02 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_application', '0002_videosource_height_videosource_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JunctionSignals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('junction_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='trafficsignal',
            name='junction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='new_application.junctionsignals'),
        ),
    ]
