# Generated by Django 5.1.5 on 2025-07-02 17:55

from django.db import migrations, models

from django.db import migrations, models

def assign_junction_to_signals(apps, schema_editor):
    """
    This function will be executed when the migration is applied.
    It retrieves the TrafficSignal and JunctionSignals models
    and assigns a junction to existing TrafficSignal records.
    """
    TrafficSignal = apps.get_model('new_application', 'TrafficSignal')
    JunctionSignals = apps.get_model('new_application', 'JunctionSignals')

    # --- Choose ONE of the following strategies based on your needs ---

    # Strategy A: Assign all existing signals to a single 'Default Junction'
    # This is simple if all initial signals belong to one junction.
    print("Creating/fetching 'Default Junction'...")
    default_junction, created = JunctionSignals.objects.get_or_create(junction_name="Junction 1 - Main Street")
    if created:
        print(f"  Created new junction: '{default_junction.junction_name}' (ID: {default_junction.id})")
    else:
        print(f"  Using existing junction: '{default_junction.junction_name}' (ID: {default_junction.id})")
    signals_updated = 0
    for signal in TrafficSignal.objects.all():
        if signal.junction is None or signal.junction != default_junction: # Adjust condition as needed
            signal.junction = default_junction
            signal.save(update_fields=['junction']) # Use update_fields for efficiency
            signals_updated += 1
            # print(f"  Assigned Signal {signal.signal_id} to '{default_junction.junction_name}'")
    print(f"Assigned {signals_updated} TrafficSignals to 'Default Junction'.")




def reverse_assign_junction_to_signals(apps, schema_editor):
    """
    Optional: Function to revert the changes if the migration is unapplied.
    This might set the junction back to None or a previous default.
    """
    TrafficSignal = apps.get_model('new_application', 'TrafficSignal')
    print("Reverting junction assignments for TrafficSignals...")
    for signal in TrafficSignal.objects.all():
        signal.junction = None # Or set to a specific default if needed
        signal.save(update_fields=['junction'])
    print("Junction assignments reverted.")


class Migration(migrations.Migration):

    dependencies = [
        ('new_application', '0003_junctionsignals_trafficsignal_junction'),
    ]

    operations = [
        migrations.RunPython(assign_junction_to_signals, reverse_assign_junction_to_signals),
    ]
